---
- name: install build depends
  apt: pkg={{item}} state=latest install_recommends=no
  sudo: yes
  with_items:
  - build-essential
  - git
  - libcurl4-openssl-dev
  - libmysqlclient-dev
  - libsqlite3-dev
  - libpq-dev
  - libreadline6-dev
  - libssl-dev
  - libxml2-dev
  - libxslt1-dev
  - zlib1g-dev
  - libc6-dev
  - libyaml-dev

- name: update rbenv repo
  git: repo=git://github.com/sstephenson/rbenv.git dest={{rbenv_root}} version=v0.4.0 accept_hostkey=true

- name: add rbenv to path
  lineinfile: dest=/home/{{dev_user}}/.bash_profile line="export PATH=$HOME/.rbenv/bin:$PATH"

- name: Eval rbenv init in ~/.profile
  lineinfile: dest="~/.bash_profile" line='eval "$(rbenv init -)"'

- name: install ruby-build
  git: repo=git://github.com/sstephenson/ruby-build.git dest={{rbenv_root}}/plugins/ruby-build

- name: check ruby ruby_version installed
  shell: $SHELL -lc "rbenv versions | grep {{ruby_version}}"
  register: ruby_installed
  ignore_errors: yes

- name: install ruby ruby_version
  shell: $SHELL -lc "rbenv install {{ruby_version}}"
  when: ruby_installed|failed

- name: set global ruby {{ruby_version}}
  shell: $SHELL -lc "rbenv global {{ruby_version}}"
  when: ruby_installed|failed

- name: rehash
  shell: $SHELL -lc "rbenv rehash"
  when: ruby_installed|failed
