- name: Get apt key
  apt_key: state=present keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D
  
- name: Configure docker apt source
  lineinfile: dest=/etc/apt/sources.list.d/docker.list line="deb https://apt.dockerproject.org/repo debian-wheezy main"
  
- name: Install docker
  apt: update_cache=yes name=docker-engine
  
- name: Start docker service
  service: name=docker state=started
  
- name: Create docker group
  group: name=docker state=present
  
- name: Add user to group
  user: name={{ dev_user }} group=docker append=yes
