---
- name: ensure apt cache is up to date
  apt: update_cache=yes
  sudo: yes

- name: ensure packages are installed
  apt: name={{item}}
  sudo: yes
  with_items:
    - postgresql
    - libpq-dev
    - python-psycopg2
    - postgresql-contrib

- name: Ensure the PostgreSQL service is running service
  service: name=postgresql state=started enabled=yes
