---
- name: download phantomjs
  get_url: url=https://bitbucket.org/ariya/phantomjs/downloads/{{ phantomjs }}.tar.bz2
           dest=/var/tmp/{{ phantomjs }}.tar.bz2
- name: untar phantomjs
  shell: chdir=/var/tmp tar xjf {{ phantomjs }}.tar.bz2 creates=/var/tmp/{{ phantomjs }}
- name: symlink the phantomjs executable
  file: dest=/usr/bin/phantomjs src=/var/tmp/{{ phantomjs }}/bin/phantomjs state=link
  sudo: yes
