
---
- hosts: all
  user: tfwright
  sudo: true
  vars_files:
    - vars/defaults.yml
 
  roles:
    - { role: rbenv, tags: ["rbenv"] } 

  pre_tasks:
    - name: Update apt package cache
      apt: update_cache=yes cache_valid_time=3600
    - name: Upgrade apt packages
      apt: upgrade=yes update_cache=yes cache_valid_time=300
