
---
- hosts: all
  user: tfwright
  sudo: false
  vars:
    dev_user: tfwright
 
  roles:
    - { role: dotfiles, tags: ["dotfiles"] } 
    - { role: rbenv, tags: ["rbenv"] } 
    - { role: vim, tags: ["vim"] } 
    - { role: postgresql, tags: ["postgresql", "db"] } 
    - { role: redis, tags: ["redis", "db"] } 
    - { role: docker, tags: ["docker"] } 

