
---
- hosts: all
  user: tfwright
  sudo: false
  vars:
    dev_user: tfwright
 
  roles:
    - { role: dotfiles, tags: ["dotfiles"] } 
    - { role: rbenv, tags: ["rbenv"] } 
    - { role: vim, tags: ["vim"] } 

