---
- hosts: all
  user: root

  vars_prompt:
    - name: "password_from_prompt"
      prompt: "Enter a password for the dev user"
      private: yes
      encrypt: "sha512_crypt"
      confirm: yes
      salt_size: 7

  roles:
    - { role: sshd, tags: ["ssh", "setup"] }

  pre_tasks:
    - name: Update apt package cache
      apt: update_cache=yes cache_valid_time=3600
    - name: Upgrade apt packages
      apt: upgrade=yes update_cache=yes cache_valid_time=300
